### ISSUE TITLE
Feature Request: Error bar option SEM

### ISSUE THREAD

**Issue by HyperionRises** [JoachimGoedhart/SuperPlotsOfData#4]
Hi,

Would it be possible to add SEM as one of the options for error bars in the plotting? It's already calculated in the statistics output, so I wonder why it's not an option to plot also. If this could be added, that'd be great.

Thanks a lot,

Best regards

**Comment by JoachimGoedhart** [comment]
Hi,

Thanks for the suggestion. My hesitation is that the s.e.m. produces the smallest error bars and that it is often (mis)used because of this. Personally, I think 95%CI is a better indicator, since it can be used to do 'inference by eye':
-https://rupress.org/jcb/article/177/1/7/34602/Error-bars-in-experimental-biology
-https://pubmed.ncbi.nlm.nih.gov/15740449/

The counter argument would be that it is very instrumental to be able to show them and be able to quickly toggle between the different options. Therefore, I implemented "Mean & s.e.m." as an option in the most recent commit:
https://github.com/JoachimGoedhart/SuperPlotsOfData/commit/ae403bb2a48f9a1984254ce4ec69142a5b5c027d

App available here for testing: https://goedhart.shinyapps.io/SuperPlotsOfData/
Let me know if it works as expected!

Cheers,
Joachim.

**Comment by JoachimGoedhart** [comment]
Thanks for the fix @quantixed !
The web apps have been updated with the correct display of 95%CI or s.e.m., see:
[https://goedhart.shinyapps.io/SuperPlotsOfData/](https://goedhart.shinyapps.io/SuperPlotsOfData/)
[https://goedhart.shinyapps.io/SuperPlotsOfData/](https://huygens.science.uva.nl/SuperPlotsOfData/)
